const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com", "mailinator.org", "mailinator.net",
  "guerrillamail.com", "guerrillamail.info", "guerrillamail.biz",
  "guerrillamail.de", "guerrillamail.net", "guerrillamail.org", "grr.la",
  "tempmail.com", "tempmail.de", "tempmail.eu", "tempmail.it",
  "tempmail.us", "tempmail2.com", "temp-mail.de", "temp-mail.org",
  "temp-mail.ru", "tempemail.com", "tempemail.net", "tempemail.co.za",
  "tempr.email", "tempail.com", "tempalias.com", "tempinbox.com",
  "tempinbox.co.uk", "tempomail.fr", "temporarily.de", "temporaryemail.net",
  "temporaryemail.us", "temporaryinbox.com", "temporarymail.org",
  "tempthe.net", "tempymail.com", "mytempemail.com", "mytempmail.net",
  "10minutemail.com", "my10minutemail.com", "10minutemail.net",
  "10minutemail.org", "zehnminutenmail.de",
  "throwaway.email", "throwam.com", "throam.com", "thrott.com",
  "throwaymail.com",
  "yopmail.com", "yopmail.fr", "yopmail.net",
  "maildrop.cc", "sharklasers.com", "spam4.me",
  "trashmail.com", "trashmail.at", "trashmail.io", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.xyz", "trashmailer.com",
  "trashspam.com", "trashemails.de", "trashimail.com", "trashdevil.com",
  "trashdevil.de",
  "discard.email", "discardmail.com", "discardmail.de", "dispostable.com",
  "fakeinbox.com", "fakemail.net", "mailexpire.com",
  "spambox.us", "spambox.info", "spambox.org",
  "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spam.la", "spam.su", "spambob.com", "spambog.com",
  "spambog.de", "spambog.ru", "spamcannon.com", "spamcero.com",
  "spamcon.org", "spamcowboy.com", "spamday.com", "spamex.com",
  "spamfree.eu", "spamfree24.de", "spamfree24.eu", "spamfree24.info",
  "spamfree24.net", "spamfree24.org", "spamgoes.in", "spamhereplease.com",
  "spamhole.com", "spamify.com", "spamkill.info", "spaml.com",
  "spaml.de", "spammotel.com", "spamoff.de", "spamslicer.com",
  "spamspot.com", "spamstack.net", "spamwc.de",
  "mailnull.com", "mailnull.net", "mailnew.com", "mailscrap.com",
  "mailsiphon.com", "mailslapping.com", "mailzilla.com", "mailzilla.org",
  "mailtemp.info", "mailerme.net", "mailmoat.com", "mailme.ir",
  "mailmetrash.com", "mailincubator.com", "mailismagic.com",
  "mailpick.biz", "mailrock.biz", "mailboxer.ru",
  "nada.email", "shortmail.net", "pookmail.com", "pop3.xyz",
  "quickinbox.com", "rhyta.com", "mohmal.com",
  "objectmail.com", "obobbo.com", "opayq.com", "owlpic.com",
  "pancakemail.com", "gishpuppy.com", "safetymail.info",
  "secretemail.de", "sausen.com", "saynotospams.com",
  "sibmail.com", "slapsfromlastnight.com", "slopsbox.com",
  "snakemail.com", "sneakemail.com", "spoofmail.de",
  "tafmail.com", "talkinator.com", "teewars.org", "teleworm.com",
  "teleworm.us", "tilien.com", "tittbit.in", "tizi.com",
  "tmail.ws", "tmailinator.com", "toiea.com", "trbvm.com",
  "trickmail.net", "trmailbox.com", "trollproject.com",
  "ub0.cc", "uggsrock.com", "ulaptop.com", "unmail.ru",
  "venompen.com", "verifymail.win", "vomoto.com",
  "walala.org", "walkmail.net", "walkmail.ru", "webemail.me",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "willselfdestruct.com", "wmail.cf", "wuzupmail.net",
  "xagloo.com", "xents.com", "xmaily.com", "xoxy.net",
  "yapped.net", "yomail.info", "z1p.biz", "zetmail.com",
  "zippymail.info", "zoaxe.com", "zoemail.net", "zoemail.org",
  "klzlk.com", "mbx.cc", "meltmail.com", "mt2009.com", "mt2014.com",
  "nomail.pw", "nomail2me.com", "nospam4.us", "nospamfor.us",
  "nowmymail.com", "nekto.net", "nicebush.com", "noclickemail.com",
  "oneoffemail.com", "onewaymail.com", "recycler.com", "re-gister.com",
  "prtnx.com", "service.ms", "stuffmail.de", "supermailer.jp",
  "suremail.info", "svk.jp", "tomisdead.com",
]);

const FUN_ERRORS = [
  "That's a disposable email! We promise we won't spam you — use your real address. 📬",
  "Hmm, that inbox has the lifespan of a mayfly. Got a real email? 🪰",
  "Nice try with the temp email! We're not a throwaway app either. 😄",
  "That email will self-destruct before we can say hello. Use something permanent! 💥",
  "We see that sneaky disposable address! Your real inbox is safe with us. 👀",
  "That domain is basically digital fast food — gone before you finish signing up. Real email please! 🍔",
  "A temp email for a finance app? Bold move! Use your actual inbox instead. 💪",
];

export function getFunDisposableError(email: string): string | null {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) return "Please enter a valid email address.";
  if (DISPOSABLE_DOMAINS.has(domain)) {
    const idx = domain.length % FUN_ERRORS.length;
    return FUN_ERRORS[idx];
  }
  return null;
}
